
before_all do
  # admin only can add slack services  
  # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

  cocoapods
end



lane :test do
  # xctest
  # snapshot
end


lane :crashlytics do
  # ensure_git_status_clean
  
  ## might introduce extra level of mess in developer portal and invalid all provisioning porfiles - experiment more!   
  # cert(
  #  output_path: "build"
  # )
  
  sigh(
    adhoc: true,
    provisioning_name: "FastlaneTest_AdHoc",
    output_path: "build"
  )
  
  gym(
    clean: true,
    configuration: "AdHoc",
    scheme: "FastlineTest",
    output_directory: "build"
  )    
  
  crashlytics({
    crashlytics_path: './Pods/Crashlytics/Crashlytics.framework',
    api_token: ENV['CRASHLYTICS_API_TOKEN'],
    build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
    # groups: "Expansoft",
    notifications: "YES"
  })
  
end




lane :appstore do
  # sigh
  # deliver
end


after_all do |lane|
  # This block is called, only if the executed lane was successful
  # slack({
  #   message: "Successfully deployed new App Update for [App](http://link.com).",
  #   success: true,
  #   channel: 'development'
  # })
end


error do |lane, exception|
  # Something bad happened
end